# About the Authors {-}

The authors have decades of combined experience in data analysis for genomics. They are developers of Bioconductor packages such as [**methylKit**](https://bioconductor.org/packages/release/bioc/html/methylKit.html), [**genomation**](https://bioconductor.org/packages/release/bioc/html/genomation.html), [**RCAS**](https://bioconductor.org/packages/release/bioc/html/RCAS.html) and [**netSmooth**](https://bioconductor.org/packages/release/bioc/html/netSmooth.html). In addition, they have played key roles in developing end-to-end genomics data analysis pipelines for RNA-seq, ChIP-seq, Bisulfite-seq, and single cell RNA-seq called [PiGx](http://bioinformatics.mdc-berlin.de/pigx/).


[*Dr. Altuna Akalin*](https://github.com/al2na) wrote most of the book and edited the rest. Altuna is a bioinformatics scientist and the head of Bioinformatics and Omics Data Science Platform at the Berlin Institute of Medical Systems Biology, Max Delbrück Center in Berlin. He has been developing computational methods for analyzing and integrating large-scale genomics data sets since 2002. He is interested in using machine learning and statistics to uncover patterns related to important biological variables such as disease state and type. He lived in the USA, Norway, Turkey, Japan, and Switzerland in order to pursue research work and education related to computational genomics. The underlying aim of his current work is utilizing complex molecular signatures to provide decision support systems for disease diagnostics and biomarker discovery. In addition to the research efforts and managing a scientific lab, since 2015, he has been organizing and teaching at computational genomics courses in Berlin with participants from across the world. This book is mostly a result of material developed for those and previous teaching efforts.

 

### Contributing Authors

[*Dr. Bora Uyar*](https://github.com/borauyar) contributed "RNA-seq Analysis" chapter. Bora started his bioinformatics training in Sabanci University (Istanbul/Turkey), from where he got his undergraduate degree. Later, he obtained MSc from Simon Fraser University (Vancouver/Canada), then a PhD from the European Molecular Biology Laboratory in Heidelberg/Germany. Since 2015, he has been working as a bioinformatics scientist at the Bioinformatics Platform and Omics Data Science Platform at the Berlin Institute for Medical Systems Biology. He has been contributing to the bioinformatics platform through research, collaborations, services and data analysis method development. His current primary research interest is the integration of multiple types of omics datasets to discover prognostic/diagnostic biomarkers of cancers. 


[*Dr. Vedran Franke*](https://github.com/frenkiboy) contributed "ChIP-seq Analysis" chapter. Vedran Franke received his PhD from University of Zagreb. His work focused on the biogenesis and function of small RNA molecules during early embryogenesis, and establishment of pluripotency. Prior to his PhD, he worked as a scientific researcher under Boris
Lenhard in University of Bergen, Norway, focusing on principles of gene enhancer functions. He continues his research in the
Bioinformatics and Omics Data Science Platform in Berlin Institute for Medical System Biology. He develops tools for multi-omics data integration, with the focus on single cell RNA sequencing, and epigenomics. His integrated knowledge of cellular physiology along with his proficiency in data analysis enables him to find creative solutions to difficult biological problems.

[*Dr. Jonathan Ronen*](https://github.com/jonathanronen) contributed "Multi-omics Analysis" chapter. Jonathan got his MSc. in control engineering from the Norwegian University of Science and Technology in 2010. He then worked as a software developer in Oslo, Brussels, and Munich. During that time, he was also on the founding team of www.holderdeord.no, a website that links votes in the Norwegian parliament to pledges made in party manifestos. In 2014-2015, Jonathan worked as a data scientist in New York University's Social Media and Political Participation lab. During that time, he also launched www.lahadam.co.il, a website which tracked Israeli politician's facebook posts. Jonathan obtained a PhD in computational biology in 2020, where he has published tools for imputation for single cell RNA-seq using priors, and integrative analysis of multi-omics data using deep learning.


