\frontmatter

## How to contribute {-}

We have been developing this book on github and your contributions are very welcome. We believe more eyes looking at this will increase the quality. There are a number of ways you can help make the
book better:

* If you don't understand something, please 
  [let Altuna know](mailto:aakalin@gmail.com). Your feedback on what is confusing
  or hard to understand is valuable.

* If you spot a typo, feel free to edit the underlying page and send a pull 
  request. If you've never done this before, the process is very easy: 
  
    * Click the edit this page on the top bar of the book website. The icon is near the search and download icons on the top of the page.
  
    * Make the changes using GitHub's in-page editor (fixing typos is
      perfectly adequate).
      
    * Include a brief description of your changes in the area below the
      editor, then propose the file change. If you make significant changes,
      include the phrase "I assign the copyright of this contribution to
      Altuna Akalin" - We need this so I can publish the printed book.
    
    * Create a pull request.
